# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79e3688c11d77dddf81012d14c3d32032311ff41f2be259dffe0b8bb2b492638ea127f5ce8900b5116d0b6b35dae5865f5c54aa059f96b8ed9ebb29c30297877

test:
  secret_key_base: 8e66e5e9b54466f519505edf3d1dafc4391768341e2953451322016a631151616633240b5e3041fd242c8c03f1b293683b3586182d2ad1f904efc2cf7fb05e36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
